# @package _global_

defaults:
  - _self_
  - datamodule: cifar10.yaml # choose data with `test_dataloader()` for evaluation
  - model: timm.yaml
  - trainer: default.yaml
  - paths: default.yaml

task_name: "eval"

train: False

test: True

compile: False

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.root_dir}/ckpt/epoch1.ckpt